apiVersion: v2
name: contoso-motors
description: A Helm chart to deploy components for the Contoso Motors scenario
type: application
version: 0.1.7
appVersion: "1.16.1"
dependencies:
  - name: ovms
    version: 0.1.0
    repository: "file://../ovms"
  - name: influxdb
    version: 0.1.0
    repository: "file://../influxdb"
  - name: rtsp-simulator  
    version: 0.1.0
    repository: "file://../rtsp-simulator"
  - name: flask-app
    version: 0.1.7
    repository: "file://../flask-app"
